USE [master]
GO
/****** Object:  Database [LogEngine]    Script Date: 23/07/2018 19:32:28 ******/
CREATE DATABASE [LogEngine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LogEngine', FILENAME = N'/var/opt/mssql/data/LogEngine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LogEngine_log', FILENAME = N'/var/opt/mssql/data/LogEngine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [LogEngine] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LogEngine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LogEngine] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LogEngine] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LogEngine] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LogEngine] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LogEngine] SET ARITHABORT OFF 
GO
ALTER DATABASE [LogEngine] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LogEngine] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LogEngine] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LogEngine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LogEngine] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LogEngine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LogEngine] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LogEngine] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LogEngine] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LogEngine] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LogEngine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LogEngine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LogEngine] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LogEngine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LogEngine] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LogEngine] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LogEngine] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LogEngine] SET RECOVERY FULL 
GO
ALTER DATABASE [LogEngine] SET  MULTI_USER 
GO
ALTER DATABASE [LogEngine] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LogEngine] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LogEngine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LogEngine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LogEngine] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'LogEngine', N'ON'
GO
ALTER DATABASE [LogEngine] SET QUERY_STORE = OFF
GO
USE [LogEngine]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [LogEngine]
GO
/****** Object:  User [LogEngine]    Script Date: 23/07/2018 19:32:28 ******/
CREATE USER [LogEngine] FOR LOGIN [LogEngine] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [LogEngine]
GO
/****** Object:  Table [dbo].[Aluno]    Script Date: 23/07/2018 19:32:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aluno](
	[IdAluno] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](300) NOT NULL,
	[Descricao] [nvarchar](max) NULL,
 CONSTRAINT [PK_Aluno] PRIMARY KEY CLUSTERED 
(
	[IdAluno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AlunoTurma]    Script Date: 23/07/2018 19:32:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlunoTurma](
	[IdAluno] [int] NOT NULL,
	[IdTurma] [int] NOT NULL,
 CONSTRAINT [PK_AlunoTurma] PRIMARY KEY CLUSTERED 
(
	[IdAluno] ASC,
	[IdTurma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoTurma]    Script Date: 23/07/2018 19:32:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoTurma](
	[IdTipoTurma] [int] NOT NULL,
	[Nome] [nvarchar](300) NOT NULL,
	[Descricao] [nvarchar](max) NULL,
 CONSTRAINT [PK_TipoTurma] PRIMARY KEY CLUSTERED 
(
	[IdTipoTurma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Turma]    Script Date: 23/07/2018 19:32:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Turma](
	[IdTurma] [int] IDENTITY(1,1) NOT NULL,
	[TipoTurma] [int] NOT NULL,
	[Nome] [nvarchar](300) NOT NULL,
	[Descricao] [nvarchar](max) NULL,
 CONSTRAINT [PK_Turma] PRIMARY KEY CLUSTERED 
(
	[IdTurma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AlunoTurma]  WITH CHECK ADD  CONSTRAINT [FK_AlunoTurma_Aluno] FOREIGN KEY([IdAluno])
REFERENCES [dbo].[Aluno] ([IdAluno])
GO
ALTER TABLE [dbo].[AlunoTurma] CHECK CONSTRAINT [FK_AlunoTurma_Aluno]
GO
ALTER TABLE [dbo].[AlunoTurma]  WITH CHECK ADD  CONSTRAINT [FK_AlunoTurma_Turma] FOREIGN KEY([IdTurma])
REFERENCES [dbo].[Turma] ([IdTurma])
GO
ALTER TABLE [dbo].[AlunoTurma] CHECK CONSTRAINT [FK_AlunoTurma_Turma]
GO
ALTER TABLE [dbo].[Turma]  WITH CHECK ADD  CONSTRAINT [FK_Turma_TipoTurma] FOREIGN KEY([TipoTurma])
REFERENCES [dbo].[TipoTurma] ([IdTipoTurma])
GO
ALTER TABLE [dbo].[Turma] CHECK CONSTRAINT [FK_Turma_TipoTurma]
GO
USE [master]
GO
ALTER DATABASE [LogEngine] SET  READ_WRITE 
GO
